### PR TITLE
Feature/if else

### LINKED ISSUE #39: Implement if_else
For Jared, let's dive in by implementing `if_else`. I think a good first goal is to get this going using an arbitrary function name. In spark this is `when(predicate, result).otherwise(alternative)`.

### PR DESCRIPTION
**Pull request by estern95**
ifelse mvp
closed #39

### CODE REVIEW

**Comment by estern95** [comment]
Made some more edits. Got case_when working with docs and testing. This closes #20.

**Comment by danzafar** [comment]
SO we are pretty close here, and I might just close it, but it looks like all these are passing except those that deal with n() and ONLY when I run all the tests at once. If I run them individually or using `devtools::test_file` they run fine. I think the issue is probably not related to this feature though.

**Comment by danzafar** [comment]
tests not passing was of no fault of this feature addition, but i went ahead and did some housekeeping to get everything passing and more streamlined. Will close this.

**Comment by danzafar** [comment]
ok i decided to go ahead and fix the error handling using the `spark_class` function. I also discovered @estern95 that this function does not work for aggregates, like if you are getting the `max(<some_col>) < <some_value>`. We should probably fix that and then add some more tests and we should be good2go.

**Review by danzafar — CHANGES_REQUESTED** [review]
lets get some better tests in `case_when` and makes sure this can handle aggregate expressions.

**Review by danzafar — APPROVED** [review]

**Comment by danzafar** [comment]
OK I fixed error handling and made the tests bomb. As of now, if_else and case_when do not handle aggregates, meaning an expression like this will not work:

```
spark_tbl(iris) %>%
  mutate(z = if_else(max(Petal_Width) > 3, T, F) %>%
  collect
```

But I have gone to great lengths so that the error is informative and provides a nice workaround.

**Pull request merged**
