### PR TITLE
Add ML Support

### LINKED ISSUE #31: get ML API working and properly tested
Creating this issue to keep track of what we're working on

### PR DESCRIPTION
**Pull request by estern95**
supervised approaches are finished on first pass

### CODE REVIEW

**Review by danzafar — CHANGES_REQUESTED** [review]
actual code looks great, can you update test-ml.R to not fail when it's run? Also, looks like we need to create a `tidyspark` function for summary :)

**Comment by danzafar** [comment]
Hey @estern95 once we get these tests sorted out we can go ahead and pull in. I might use your branch to publish a `summary` function for these object types.

**Comment by estern95** [comment]
I fixed the tests :) I royally screwed up my java installation today :) that was fun

**Comment by danzafar** [comment]
hey @estern95 when I do `load_all` on this branch I get message:
```
 Error in setMethod("ml_perplexity", signature(object = "LDAModel", data = "SparkDataFrame"),  : 
  no existing definition for function ‘ml_perplexity’ 
```

Any idea? By the way I'm thinking to just port over SparkR's tests for this. They seem conprehensive. https://github.com/apache/spark/blob/master/R/pkg/tests/fulltests/test_mllib_regression.R

**Pull request closed without merging**
